### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by Lechus** [marcojanssen/vagrant-puppet-jenkins#2]
What is the login/password for vm?

**Comment by Lechus** [comment]
OK, Found it. "vagrant"

**Comment by marcojanssen** [comment]
vagrant/vagrant, but you found it yourself :)

Make sure you use vagrant 1.2.7. Somehow Ubuntu ringtail & vagrant 1.3> don't work together

**Comment by marcojanssen** [comment]
and for root

``` bash
sudo su
```
